version: '3.4'

services:
  mysql-datbase:
    image: mysql:8.0.24        
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - backend-network
    volumes: 
      - mysql-data-volume:/var/lib/mysql

networks:
  backend-network: {}

volumes:
  mysql-data-volume:
    external:
      name: mysql-data-volume