version: '3.4'

services:
  postgres-database:
    image: postgres:13.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: locations
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - backend-network
    volumes: 
      - type: volume
        source: postgres-data-volume
        target: /var/lib/postgresql/data
        volume:
          nocopy: true

networks:
  backend-network: 

volumes:
  postgres-data-volume: