version: '3.8'
services:
  mongodb-service:
    container_name: mongodb-service
    image: mongo:4.4.6
    ports:
    - 27017:27017
    networks:
      - backend-network
    volumes:
      - mongo-data-volume:/data/db
      - mongo-config-volume:/data/configdb

networks:
  backend-network:
volumes:
  mongo-data-volume:
  mongo-config-volume: