version: '3.8'

networks:
  default:

services:
  db:
    image: mysql:8.0
    container_name: library
    ports:
      - "3306:3306"
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: Pa55w0rd!
      MYSQL_DATABASE: library_db